"""altera status aberto para pendente

Revision ID: 37702e25c4d2
Revises: f6031c71a88c
Create Date: 2026-09-21 11:26:59.355230

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '37702e25c4d2'
down_revision: Union[str, Sequence[str], None] = 'f6031c71a88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE statuschamado RENAME TO statuschamado_old")

    op.execute("""
        CREATE TYPE statuschamado AS ENUM (
            'Novo',
            'Pendente',
            'Em andamento',
            'Encerrado',
            'Cancelado'
        )
    """)

    op.execute("""
        ALTER TABLE chamados
        ALTER COLUMN status
        TYPE TEXT
        USING status::text
    """)

    op.execute("""
        UPDATE chamados
        SET status = 'Pendente'
        WHERE status = 'Aberto'
    """)

    op.execute("""
        ALTER TABLE chamados
        ALTER COLUMN status
        TYPE statuschamado
        USING status::statuschamado
    """)

    op.execute("DROP TYPE statuschamado_old")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
