"""adiciona tabela de historicos

Revision ID: 728c33fd7f11
Revises: 37702e25c4d2
Create Date: 2026-09-22 13:35:26.971031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728c33fd7f11'
down_revision: Union[str, Sequence[str], None] = '37702e25c4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicos_chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('Alteração', 'Anotação', name='tipohistorico'), nullable=False),
    sa.Column('visibilidade', sa.Enum('Público', 'Interno', name='visibilidadehistorico'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historicos_chamados')
    # ### end Alembic commands ###
